### ISSUE TITLE
`onscreen` not working for me

### ISSUE THREAD

**Issue by fhaust** [abarbu/matplotlib-haskell#2]
The `onscreen` way of displaying graphs does not work for me. Neither by calling it interactively from `ghci` nor from a compiled program. The (Haskell) program just stops apparently waiting for the python subprocess to end.

If edit the emitted script in the tmp folder manually and remove these lines:

    pid = os.fork()
    if(pid != 0):
      exit(0)
    plot.draw()

I can call it manually but with them it just ends after a while.

**Comment by fhaust** [comment]
Just noticed that the related `pyDetach` function is documented as "does not work reliable". Maybe create the process in a Haskell thread and handle forking there?

**Comment by abarbu** [comment]
Yeah.. Guess we're going to have to go the process route! I'll get to it later in the week.
I wonder why they have an API call that's not reliable?

**Comment by abarbu** [comment]
Things should work now. There's a race condition in how files a read. I changed python to not detach and to fork in Haskell instead. Let me know if that fixes things.

**Comment by LukaHorvat** [comment]
It works for me.

**Comment by fhaust** [comment]
Hmm ... does not work for me. But honestly I am not sure if I got the latest version. Will check that out tomorrow maybe.

**Comment by abarbu** [comment]
That could be. The stackage nightly and lts haven't been regenerated yet since I pushed this. should be another day for one and a week or os for the other. Let me know.

**Comment by fhaust** [comment]
I actually pointed stack at the github repository. But as I said I am not sure that worked.

**Comment by jchia** [comment]
On 17425a831b254b4ef2cafdfe2edabf832058882d, I had to `threadDelay 1` after `onscreen` for the plot to appear. If `main` is just `onscreen ...` without the `threadDelay 1`, the program exits without showing the plot.

**Comment by abarbu** [comment]
Ok. I'll make a more permanent solution with a lockfile to eliminate these race conditions when I get some free time this weekend.

**Comment by abarbu** [comment]
Hi folks, I'm going to close this as it's been a long time. Hopefully the ecosystem is more stable now and these problems have gone away. Feel free to reopen.

**Comment by shlok** [comment]
> On [17425a8](https://github.com/abarbu/matplotlib-haskell/commit/17425a831b254b4ef2cafdfe2edabf832058882d), I had to `threadDelay 1` after `onscreen` for the plot to appear. If `main` is just `onscreen ...` without the `threadDelay 1`, the program exits without showing the plot.

This solution worked for me (however, I had to increase the delay to 10).

**Comment by vlyr** [comment]
> On [17425a8](https://github.com/abarbu/matplotlib-haskell/commit/17425a831b254b4ef2cafdfe2edabf832058882d), I had to `threadDelay 1` after `onscreen` for the plot to appear. If `main` is just `onscreen ...` without the `threadDelay 1`, the program exits without showing the plot.

Also worked for me. I did have to set the delay to 3000 though.
