### ISSUE TITLE
Allow use of seaborn functions to expand plotting functionality.

### ISSUE THREAD

**Issue by GregorySchwartz** [abarbu/matplotlib-haskell#7]
While this addition would be nice, I wouldn't know how to do so without adding seaborn to the dependencies when installing.

**Comment by abarbu** [comment]
I think seaborn support might be better as a separate package that depends on this one. Should be easy to do. In the long term matplotlib seems stable. Seaborn is more experimental, more likely to break, and to stop being maintained.
