### ISSUE TITLE
Allow user to specify Python location

### ISSUE THREAD

**Issue by bradrn** [abarbu/matplotlib-haskell#9]
At the moment, the command used to call Python is hardcoded:

https://github.com/abarbu/matplotlib-haskell/blob/9b85f54cfefa993b34de9657a0a97327b1b9915b/src/Graphics/Matplotlib/Internal.hs#L326

However, this means that occasionally, the wrong Python gets called. For instance, my system has at least two Python installations which I know of: a global installation (with `matplotlib` installed), and an installation in `stack`’s MSYS2 (with `matplotlib` not installed). `matplotlib-haskell` consistently calls `stack`’s Python, which doesn’t have `matplotlib` installed; I would prefer that it calls my global Python installation, which does have `matplotlib` installed. Would it be possible to add a feature to allow this, by letting the user specify the location of the Python executable they want?

**Comment by abarbu** [comment]
I'm sympathetic and not opposed, but I worry that this will cause a flood of long-term problems.

Any code that explicitly lists the path to your python binary will be broken on other machines and you won't discover this until you push. This is really an issue with any kind of external dependency since something has to look up that dependency somewhere. In this case, we do the same thing that is recommended when running any python script: `#!/usr/bin/env python`

If you change this, it will also cause very subtle breakage for you too. If you use anaconda or virtualenv you will use the wrong binary but in a hidden way, you'll have to potentially look at every call to figure out which one lists the wrong binary. Worse, that binary might be read in from a configuration file.

I think you have several far better and more standardized solutions: install matplotlib in the actual environment you will be using or change your path environment to point to the correct python library.

**Comment by bradrn** [comment]
Good point about there being problems with this. I suppose I was thinking more about interactive exploration in GHCi — I have an interesting set of numbers, now I want to plot them with matplotlib to see if they look interesting. Under those situations, it’s absolutely fine to change the path to the executable for one line of a GHCi session. But you’re right in that this leads to problems when this is used in anything more permanent.

> I think you have several far better and more standardized solutions: install matplotlib in the actual environment you will be using

This was the very first thing I tried. But when I tried installing it, `matplotlib` gave me a weird error and refused to install. Googling it didn’t help — I didn’t find anyone who got the same error. And I don’t know the intricacies of Python package management (I’m not interested in learning any more Python, I just want to do some plotting in Haskell!), so I never got any further than that. At this point, I’ve given up on installing `matplotlib` in the environment GHCi is using.

> or change your path environment to point to the correct python library.

That could be problematic. When I run `stack ghci` and list the PATH, this is what I get:

```
> getEnv "PATH" >>= (mapM_ putStrLn . splitOn ";")
C:\sr\global-project\.stack-work\install\7722ed74\bin
C:\sr\snapshots\9d7ee612\bin
C:\sr\compiler-tools\x86_64-windows\ghc-8.8.3\bin
C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\bin
C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3\mingw\bin
C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin
C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\usr\bin
C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\usr\local\bin
C:\Program Files\PowerShell\7
etc.
```

Note that `stack` inserts a bunch of directories on its own at the beginning of PATH. This is useful, as it lets me access various utilities on these paths using `stack exec`, but in this case it’s an inconvenience as it causes me to use `stack`’s Python installation (without `matplotlib`) rather than my own global installation (with `matplotlib`). If there is a way to disable this, then I don’t know it. (Sometimes you can do it with `--no-ghc-package-path`, but as far as I’m aware that only works with `stack exec`.) And even if I could, I would still run into problems: the command which `matplotlib-haskell` runs is `env python3 code.py` (I think), whereas I need to run `python code.py`. So I would still need to customise the executable name even if I could customise the PATH.

**Comment by mklinik** [comment]
I'm not sure if this would help, but I'm using `virtualenv` with matplotlib. I create a new virtualenv in each haskell project that uses matplotlib, `pip install matplotlib scipy` there, and then `stack run` from within that virtualenv. I'm no python expert, but I believe this should make sure that you call the right python if you have multiple ones.

Like so:

```
mkl@xps13 ~/s/h/data-visualization$ virtualenv venv
created virtual environment CPython3.9.6.final.0-64 in 65ms
  creator CPython3Posix(dest=/home/mkl/sandbox/haskell-misc/data-visualization/venv, clear=False, no_vcs_ignore=False, 
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/mkl/.loc
    added seed packages: pip==21.1.3, setuptools==57.4.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
mkl@xps13 ~/s/h/data-visualization$ source venv/bin/activate
(venv) mkl@xps13 ~/s/h/data-visualization$ pip install matplotlib scipy
Collecting matplotlib
  Using cached matplotlib-3.4.3-cp39-cp39-manylinux1_x86_64.whl (10.3 MB)
Collecting scipy
  Using cached scipy-1.7.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.5 MB)
---- SNIP ----
(venv) mkl@xps13 ~/s/h/data-visualization$ stack run

```

**Comment by bradrn** [comment]
I’ve been using Python quite a lot lately, so I decided to have another look at `matplotlib-haskell` to see if I could get it to work with my newfound experience. I’m using Anaconda as a package manager now, so I was curious to see if that made any changes. Alas, it still errors out:

```
Traceback (most recent call last):
  File "C:\Users\bradn\AppData\Local\Temp\cod1A16.py", line 1, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

(On the other hand, it’s been too long since my first post here for me to remember the exact error I originally had, so this may possibly be a completely different error to what I first reported.)

One idea I thought of: if the problem is with Stack adding its own paths to PATH, would it have any effect if I used `setEnv` to re-add Anaconda paths within GHCi? Unfortunately, I still got exactly the same error after doing this, so I’m not too sure anymore if this was the cause of the error I’m getting.

**Comment by abarbu** [comment]
How odd. I use this package with stack all the time, admittedly, on Linux not Windows. I've used it with both virtualenv and with conda without issues.

PATH shouldn't affect the lookup path for python modules. I'm assuming that just running python and importing matplotlib works?

**Comment by bradrn** [comment]
> I'm assuming that just running python and importing matplotlib works?

Huh, I tried this, and now I’m getting a totally different error:

```
>python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:37:25) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> ^Z


>stack ghci --package matplotlib
[…lots of output skipped…]
Prelude> :set -XExtendedDefaultRules
Prelude> import Graphics.Matplotlib
Prelude Graphics.Matplotlib> onscreen $ contourF (\a b -> sin (a*pi/180.0) + cos (b*pi/180.0)) (-100) 100 (-200) 200 10

Access violation in generated code when reading 0xffffffffffffffff

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x708dc90    0x9023d0b C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.4\mingw\x86_64-w64-mingw32\lib\libmingwex.a(lib64_libmingwex_a-cos.o)+0x6b
 * 0x708dc98    0x9023cfd C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.4\mingw\x86_64-w64-mingw32\lib\libmingwex.a(lib64_libmingwex_a-cos.o)+0x5d
 * 0x708dca0    0x7901a80
 * 0x708dcf0    0x364a4a9 C:\Users\bradn\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.4\bin\ghc.exe+0x324a4a9
 * 0x708dcf8    0xbffe
 * 0x708dd00    0x4069000000000000
 * 0x708dd08    0xc00becde5da115a9
```

And then GHCi crashes.

**Comment by abarbu** [comment]
I'm afraid that something is wrong with your Haskell setup. Segfaults shouldn't be possible with this library.

**Comment by bradrn** [comment]
Well, I’m not aware of any problems with my Haskell setup, so I doubt that’s the problem.

**Comment by abarbu** [comment]
I've add a shell.nix which should provide python, matplotlib, and any other dependencies. Hopefully this resolves all installation issues! Feel free to reopen if you're still having problems.

**Comment by bradrn** [comment]
Unfortunately, Nix doesn’t support Windows, though it’s undoubtedly been convenient when I’ve used Linux. So as nice as it is to have Nix integration, I don’t think this will be a solution for Windows-users like me.

**Comment by abarbu** [comment]
From my understanding Nix supports Windows through WSL now. Might be worth a try.

**Comment by bradrn** [comment]
I do understand this: for a recent project, I have been successfully using Reflex via Nix on WSL. However, this still is not ‘true’ Windows support, and it is inconvenient for me to launch WSL and then the appropriate Nix environment when I just want to make a graph in GHCi.
